### ISSUE TITLE
Wall Icons Are Failing test.py

### ISSUE THREAD

**Issue by unit0016** [wall-nerds/wallening#149]
```
Failed on: ./icons/turf/smoothrocks.dmi
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/wallening/wallening/tools/dmi/test.py", line 39, in <module>
    _main()
  File "/home/runner/work/wallening/wallening/tools/dmi/test.py", line 33, in _main
    return _self_test()
  File "/home/runner/work/wallening/wallening/tools/dmi/test.py", line 16, in _self_test
    Dmi.from_file(fullpath)
  File "/home/runner/work/wallening/wallening/tools/dmi/__init__.py", line 63, in from_file
    assert next(line_iter) == f"version = {cls.version}"
AssertionError
Error: Process completed with exit code 1.
```
See https://github.com/wall-nerds/wallening/actions/runs/3349722403/jobs/5549980971, https://github.com/wall-nerds/wallening/actions/runs/3357349693/jobs/5563100078

**Comment by unit0016** [comment]
Just got another hit on ./icons/effects/frills/wall_bamboo_frill.dmi - Going to start re-saving every file linters brings up until I get a repeat OR a new error message pops up.

**Comment by LemonInTheDark** [comment]
I think? this is just from things cut using the old software. Need to check tho
